sudo: required
services:
    - docker

before_install:
    - docker build -t genavyb1/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true genavyb1/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker1"
    env: "Docker1-env"
    bucket_name: "elasticbeanstalk-us-east-2-205366435539"
    bucket_path: "docker1"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"


